name: kinodata-docked-rescore
channels:
  - conda-forge
dependencies:
  - pip
  - requests
  - numpy
  - python=3.9.13
  - pytorch::pytorch=1.12.1
  - pyg::pyg
  - pandas
  - scipy
  - tqdm
  - rdkit
  - matplotlib
  - pytorch-lightning
  - wandb
  - black
