name: kinodata-docked-rescore
channels:
  - conda-forge
dependencies:
  - pip
  - requests
  - numpy
  - python=3.10.8
  - pytorch::pytorch
  - pyg::pyg
  - pandas
  - scipy
  - tqdm
  - rdkit
  - matplotlib
  - wandb
