name: kinodata
channels:
  - conda-forge
dependencies:
  - numpy
  - pip
  - python=3.10.8
  - pytorch::pytorch
  - pyg::pyg
  - pandas
  - scipy
  - tqdm
  - rdkit
  - matplotlib
  - ipykernel
  - ca-certificates
  - certifi
  - openssl
  - black
  - wandb
  - pytorch-lightning
  - mypy
  - seaborn
  - cvxpy
  - biotite
  - biopandas
